### ISSUE TITLE
Some tests with CICE5 for CESM2_3 fail on the generate phase

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/SimpleLand#79]
Longer tests (months) fail on the generate phase because the history file name is "cice" rather than "cice5"

SMS_Lm3_Vmct.f19_f19_mg16.FLT2000ClimoC6I5Slim.cheyenne_intel.slim-Monthly	  GENERATE 	
SMS_Lm3_Vmct.f19_g16.ELT2000ClimoTESTC5I5Slim.cheyenne_gnu.slim-global_uniform_g16_SOM	  GENERATE 	
SMS_Lm3_Vmct.f19_g16.ELT2000ClimoTESTC5I5Slim.cheyenne_intel.slim-global_uniform_g16_SOM	  GENERATE 

```
2023-06-09 16:59:46: Exception during GENERATE:
ERROR: ERROR: cant find model name cice5 in SMS_Lm3_Vmct.f19_g16.ELT2000ClimoTESTC5I5Slim.cheyenne_intel.slim-global_uniform_g16_SOM.GC.slim41_cesm2_3_beta1chintelasl.cice.h.0001-03.nc
Traceback (most recent call last):
  File "/glade/work/erik/slim_cesm21/cime/CIME/SystemTests/system_tests_common.py", line 555, in _phase_modifying_call
    function()
  File "/glade/work/erik/slim_cesm21/cime/CIME/SystemTests/system_tests_common.py", line 785, in _generate_baseline
    success, comments = generate_baseline(self._case)
  File "/glade/work/erik/slim_cesm21/cime/CIME/hist_utils.py", line 666, in generate_baseline
    allow_baseline_overwrite=allow_baseline_overwrite,
  File "/glade/work/erik/slim_cesm21/cime/CIME/hist_utils.py", line 604, in _generate_baseline_impl
    offset >= 0, "ERROR: cant find model name {} in {}".format(model, hist)
  File "/glade/work/erik/slim_cesm21/cime/CIME/utils.py", line 166, in expect
    raise exc_type(msg)
CIME.utils.CIMEError: ERROR: ERROR: cant find model name cice5 in SMS_Lm3_Vmct.f19_g16.ELT2000ClimoTESTC5I5Slim.cheyenne_intel.slim-global_uniform_g16_SOM.GC.slim41_cesm2_3_beta1chintelasl.cice.h.0001-03.nc
```

**Comment by dabail10** [comment]
Can these be changed to CICE6?

**Comment by ekluzek** [comment]
@dabail10 yes we will be changing them to CICE6. And that of course is the longer term plan, since CICE5 is no longer being developed and only CICE6 is.

It will take us some time to switch. Right now we only have a working MCT cap for SLIM and are developing a NUOPC one. I was under the impression that CICE5 didn't work under MCT, but it looks like there is a MCT cap, so maybe we can get it to work even before that?

Since, CICE5 is going away I don't want to push too hard on making any changes to it, but I did need to document the issue we saw. It also looks like this issue might be easy to fix -- but I'm not sure that it's important to do so...

**Comment by dabail10** [comment]
CICE6 does not have an MCT cap. CICE5 does.

**Comment by ekluzek** [comment]
An. update here. We are now planning to remove CICE5 at least with the CESM3 release. I don't think that's a problem in principle, but we should start planning that only CICE6 will be available in CESM and for SLIM.

@marysa @islasimpson please comment if you see any issue with this.

**Comment by islasimpson** [comment]
I don't see any issues but @marysa would know better.

**Comment by marysa** [comment]
Also don't see any issues, other than making sure we have a slab ocean that is consistent with both CICE6 and CAM6, but that is not an intrinsically SLIM problem.
